### PR TITLE
Revert “Fix issue #383” and re-fix issue 383

### LINKED ISSUE #383: Panic Error When Running Load Test with Parallel
**Description**
When using a parallel script to perform a load test, the seq command encounters a panic error. feature/v0.6.0

**Logs:**

```
xlayer-seq              | [INFO] [04-02|07:40:28.266] [5/13 Execution] Starting block 128 (forkid 13)... 
xlayer-seq              | [INFO] [04-02|07:40:28.266] [5/13 Execution] Waiting for txs from the pool... 
xlayer-seq              | [INFO] [04-02|07:40:28.279] [api.generateWitness] SMT incremental progress (pre-process): 4/4 (100%) 
xlayer-seq              | [INFO] [04-02|07:40:28.309] Generating witness timing                batch=14 blockFrom=122 blockTo=127 taken=48.27675ms
xlayer-seq              | [WARN] [04-02|07:40:29.100] [rpc] served                             conn=172.18.0.1:56148 method=eth_sendRawTransaction reqid=745 t=2.41575ms err="INTERNAL_ERROR: nonce too low"
xlayer-seq              | panic: runtime error: index out of range [2] with length 2
xlayer-seq              | 
xlayer-seq              | goroutine 152 [running]:
xlayer-seq              | github.com/ledgerwatch/erigon/zk/txpool.fillDiscardReasons({0x4002941398, 0x3, 0x3}, {{0x40016954e0, 0x2, 0x2}, {0x4002bd0600, 0x28, 0x30}, {0x4002941418, ...}}, ...)
xlayer-seq              |       github.com/ledgerwatch/erigon/zk/txpool/pool.go:985 +0x100
xlayer-seq              | github.com/ledgerwatch/erigon/zk/txpool.(*TxPool).AddLocalTxs(0x4001544388, {0x2c81eb8, 0x40017784d0}, {{0x40039debc0, 0x3, 0x4}, {0x4000d962a0, 0x3c, 0x60}, {0x4002941388, ...}}, ...)
xlayer-seq              |       github.com/ledgerwatch/erigon/zk/txpool/pool.go:1041 +0x880
xlayer-seq              | github.com/ledgerwatch/erigon/zk/txpool.(*GrpcServer).Add(0x4001bd2a20, {0x2c81eb8, 0x40017784d0}, 0x40000ad900)
xlayer-seq              |       github.com/ledgerwatch/erigon/zk/txpool/txpool_grpc_server.go:229 +0x590
xlayer-seq              | github.com/ledgerwatch/erigon-lib/direct.(*TxPoolClient).Add(0x4001caafc0?, {0x2c81eb8?, 0x40017784d0?}, 0xbb5736889ac87249?, {0x2233ce0?, 0x2c81e48?, 0x4002bd23c0?})
xlayer-seq              |       github.com/ledgerwatch/erigon-lib@v1.0.0/direct/txpool_client.go:48 +0x30
xlayer-seq              | github.com/ledgerwatch/erigon/turbo/jsonrpc.(*APIImpl).processBulk(0x40011941a0, {0x4001baa000, 0x3, 0x4001c03a40?})
xlayer-seq              |       github.com/ledgerwatch/erigon/turbo/jsonrpc/send_transaction_xlayer.go:197 +0x5f4
xlayer-seq              | github.com/ledgerwatch/erigon/turbo/jsonrpc.(*APIImpl).worker.func2()
xlayer-seq              |       github.com/ledgerwatch/erigon/turbo/jsonrpc/send_transaction_xlayer.go:110 +0x150
xlayer-seq              | github.com/ledgerwatch/erigon/turbo/jsonrpc.(*APIImpl).worker(0x40011941a0)
xlayer-seq              |       github.com/ledgerwatch/erigon/turbo/jsonrpc/send_transaction_xlayer.go:143 +0x2ac
xlayer-seq              | created by github.com/ledgerwatch/erigon/turbo/jsonrpc.NewEthAPI in goroutine 1
xlayer-seq              |       github.com/ledgerwatch/erigon/turbo/jsonrpc/eth_api.go:468 +0x4bc
```

### PR DESCRIPTION
**Pull request by googgoog**
- Revert #386 
- Re-fix #383 
- Add new test case

### CODE REVIEW

File: zk/txpool/pool.go [hunk 1]
```diff
@@ -1026,12 +1024,20 @@ func (p *TxPool) AddLocalTxs(ctx context.Context, newTransactions types.TxSlots,
 		return nil, err
 	}
 
+	validIndices := make([]int, 0, len(newTxs.Txs))
+	for i, reason := range reasons {
+		reasons[i] = reason
```
Comment (fatcat22) [inline zk/txpool/pool.go:1029]: Is this line useless?

**Review by fatcat22 — APPROVED** [review]

**Review by cwbhhjl — APPROVED** [review]
